build.gradle
Android project dependencies.

implementation 'com.onedebit.chime:latest_version 
'github/workflows/jekyll-gh-pages.yml
name:transfer-quickstart
Deploy with GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2
    - name: Setup Jekyll
      uses: actions/setup-ruby@v1
    - name: Build and deploy
      run: |
        gem install jekyll
        jekyll build
        echo "Build complete"
