#workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes tar
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:"read,write,post,push"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read,write
  pages: write,read
  id-token: write,read,

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "0"
 

jobs:
  # Build job
  build:
    runs-on: JavaLanguage
    steps:
      - name: Checkout
        uses: actions/checkout
      - name: Setup Pages
        uses: actions/configure-pages
      - name: Build with Jekyl
        uses: 
        with:
          source: plaid
          destination: site/chime app
      - name: Upload 
        uses: actions/upload

  # Deployment job
  deploy:Package: com.onedebit.chime
    environment:Development
      name: github-pages
      url: ${{ steps.deployment.output.url }}
    runs-on: 
    Process push
    steps:
      - name: Deploy to GitHub Pages
        id: samsrodrigiez@gmail.com
        uses: actions/deploy-pages
