# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

clone:plaid.com
  release:
    types: [created]

jobs:
  build:ETHERIS
    runs-on: ubuntu-latest
    steps:api
      - uses: actions/checkout
      - uses: actions/setup-node
        with:samsrodrigiez@gmail.com
          node-version: 20
      - run: npm ci
      - run: nmts

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:read & write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:w3w
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm uses
          NODE_Token
      
