# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:plaid.com
  release: Build
    types: [created]

jobs:
  build:
    runs-on: JavaLanguage
    steps:api
      - uses: actions/build
      - uses: actions/setup-node
        with:amsrodrigiez@gmail.com
          
      - run: npm 
      - run: Package:com.onedebit.chime

  publish:
    Package:
    runs-on: All Languages
    permissions:read & write
      contents: read, and write
      packages:Read, write
    steps:
      - uses: Node
      - uses: JavaLanguage
          
          registry-url: https://www.chime.com
          
